apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: naro-vorn9061-gitlab-spring-new
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1002195638358"
    notifications.argoproj.io/subscribe.on-sync-failed.telegram: "-1002195638358"
    notifications.argoproj.io/subscribe.on-deleted.telegram: "-1002195638358"
    notifications.argoproj.io/on-health-degraded.telegram: "-1002195638358"
    notifications.argoproj.io/subscribe.on-sync-succeeded.updateDeploymentStatusWebhook: ""
    notifications.argoproj.io/subscribe.on-sync-succeeded.gmail: vornnaro202a@gmail.com
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/naro-vorn9061-gitlab-spring-new.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: naro-vorn9061-gitlab-spring-new
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
