apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: naro-vorn9061-gitlab-spring-new-certificate
  namespace: naro-vorn9061-gitlab-spring-new
spec:
  secretName: naro-vorn9061-gitlab-spring-new-secret-tls
  commonName: naro-vorn9061-gitlab-spring-new.assessify.org
  dnsNames:
  - naro-vorn9061-gitlab-spring-new.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
